apiVersion: v1
kind: Pod
metadata:
  name: log-monitor-ms
  namespace: choreography
  labels:
    app: log-monitor-ms
spec:
  nodeName: minikube
  containers:
  - name: log-monitor
    # get latest version of image
    image: lucasjellema/node-app-runner
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: "https://github.com/lucasjellema/2019-fontys-business-and-IT-agility-through-microservice-architecture"
    - name: APP_PORT
      value: "8115"
    - name: APP_HOME
      value: "5-microservices/LogMonitor"
    - name: APP_STARTUP
      value: "LogMonitor.js"
    - name: KAFKA_HOST
      value: "kafka.kafka-ca1"
    - name: ZOOKEEPER_PORT
      value: "9092"
    - name: KAFKA_TOPIC
      value: "logTopic"
    ports:
    # containerPort is the port exposed by the container (where nodejs express api is listening)
    - containerPort: 8115
  