apiVersion: v1
kind: Pod
metadata:
  name: event-bus-listener-ms
  labels:
    app: event-bus-listener-ms
spec:
  nodeName: minikube
  containers:
  - name: event-bus-listener
    # get latest version of image
    image: lucasjellema/node-app-runner
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: "https://github.com/lucasjellema/2019-fontys-business-and-IT-agility-through-microservice-architecture"
    - name: APP_PORT
      value: "8096"
    - name: APP_HOME
      value: "4-kafka/event-bus-listener"
    - name: APP_STARTUP
      value: "EventBusListener.js"
    # assuming Kafka was started on minikube using https://github.com/d1egoaz/minikube-kafka-cluster
    # the Zookeeper cluster is exposed through the service known as zookeeper-service.kafka-ca1 within the Minikube cluster
    - name: KAFKA_HOST
      value: "zookeeper-service.kafka-ca1"
    - name: ZOOKEEPER_PORT
      value: "2181"
    - name: KAFKA_TOPIC
      value: "event-bus"
    ports:
    # containerPort is the port exposed by the container (where nodejs express api is listening)
    - containerPort: 8096
