apiVersion: v1
kind: Pod
metadata:
  name: tweet-validator-ms
  namespace: choreography
  labels:
    app: tweet-validator-ms
spec:
  nodeName: minikube
  containers:
  - name: tweet-validator
    # get latest version of image
    image: lucasjellema/node-app-runner
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: "https://github.com/lucasjellema/2019-fontys-business-and-IT-agility-through-microservice-architecture"
    - name: APP_PORT
      value: "8102"
    - name: APP_HOME
      value: "5-microservices/ValidateTweet"
    - name: APP_STARTUP
      value: "TweetValidator.js"
    - name: KAFKA_HOST
      value: "kafka.kafka-ca1"
    - name: ZOOKEEPER_PORT
      value: "9092"
    - name: KAFKA_TOPIC
      value: "workflowEvents"
    - name: REDIS_HOST
      value: "redis-cache"
    - name: REDIS_PORT
      value: "6379"
    ports:
    # containerPort is the port exposed by the container (where nodejs express api is listening)
    - containerPort: 8102
