apiVersion: v1
kind: Pod
metadata:
  name: tweetreceiver-ms
  namespace: choreography
  labels:
    app: tweetreceiver-ms
spec:
  nodeName: minikube
  containers:
  - name: tweetreceiver
    # get latest version of image
    image: lucasjellema/node-app-runner
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: "https://github.com/lucasjellema/2019-fontys-business-and-IT-agility-through-microservice-architecture"
    - name: APP_PORT
      value: "8101"
    - name: APP_HOME
      value: "5-microservices/TweetReceiver"
    - name: APP_STARTUP
      value: "TweetReceiver.js"
    - name: KAFKA_HOST
      value: "kafka.kafka-ca1"
    - name: ZOOKEEPER_PORT
      value: "9092"
    - name: KAFKA_TOPIC
      value: "workflowEvents"
    ports:
    # containerPort is the port exposed by the container (where nodejs express api is listening)
    - containerPort: 8101
